# Generated by Django 5.0 on 2023-12-28 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
